
project_id = "gsantprpdytoyzmearrb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions.send-welcome-email]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
